name: "Crawler"

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Execute PHP script
        run: |
          php crawler.php
          git config --global user.email "ircfspace@gmail.com"
          git config --global user.name "ircfspace"
          git config credential.helper store
          git add -A
          git commit -m "🚀 Updated - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
          git push
